---
title: "Homework_04"
author: "Shelby N. Scarfo"
date: "2024-02-07"
output: 
  html_document: 
    highlight: pygments
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1:  
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

z <- x^(a^b)
print(z)
```
b.
```{r}
z <- (x^a)^b
print(z)
```
c.
```{r}
z <- 3*x^3 + 2*x^2 + 1
print(z)
```

### Question 2:  
a.
``` {r}
vec_1 <- c(seq(c(1:8)),7:1)
print(vec_1)
```
b.
``` {r}
vec_2 <- 1:5
rep(x = vec_2, times = vec_2)
```
c.
```{r}
vec_3 <- 5:1
rep(x = vec_3, times = rev(vec_3))
```

### Question 3:  
```{r}
set.seed(30)
cart <- runif(2)
polar <- sqrt((cart[1]^2)+cart[2]^2)
t <- atan(cart[2]/cart[1])
pcoords <- c(polar,t)
print(pcoords)

```
### Question 4:  
a. Queue + serpent gets in line
```{r}
queue <- c("sheep", "fox", "owl", "ant")

queue[5] <- "serpent"

print(queue)
```
b. Sheep enters ark
```{r}
queue <- queue[-1]
print(queue)
```
c. Donkey arrives and cuts to first
```{r}
queue <- c("donkey", queue)
print(queue)
```
d.Serpent leaves
```{r}
queue <- queue[-5]
print(queue)
```
e.Owl leaves
```{r}
queue <- queue[-3]
print(queue)
```
f.Aphid arrives and goes in front of ant
```{r}
queue <- c(queue[1:2], "aphid", queue[3])
print(queue)
```
g. Find the aphid
```{r}
print(which(queue == "aphid"))
```
### Question 5:
```{r}
v <- seq(1:100)
v <- v[v %% 2 != 0 & v %% 3 !=0 & v %% 7 != 0]
print(v)
```
